import { NextRequest, NextResponse } from "next/server"
import { getPool } from "@/lib/dbPool"

const pool = getPool()
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || ""

const ARC_PROJECTS = [
  { name: "Aave",                 tagline: "Open source protocol to create non-custodial liquidity markets to earn interest on supplying and borrowing",    description: "Aave is a decentralised non-custodial liquidity protocol where users can participate as depositors or borrowers. Depositors provide liquidity to earn passive income, while borrowers can borrow in an overcollateralised or undercollateralised fashion.",  twitter: "AaveAave",       category: "Lending",         website: "https://aave.com",                                          logo: "aave.com" },
  { name: "Absa",                 tagline: "Digital banking services including bank accounts, loans, and internet banking",                                  description: "Absa Group Limited is a pan-African financial services company headquartered in Johannesburg, South Africa. It offers a range of retail, business, corporate and investment banking, insurance, wealth and investment management products and services.",  twitter: "AbsaGroupLtd",   category: "Finance",         website: "https://www.absa.co.za/personal",                            logo: "absa.co.za" },
  { name: "Across",               tagline: "Fast and capital-efficient crosschain bridging protocol",                                                         description: "Across is a cross-chain bridge for moving tokens across blockchain networks. It is optimistic, fast, and secured by UMA's optimistic oracle. Across uses a network of relayers to front capital to users and settles funds on the destination chain.",          twitter: "AcrossProtocol", category: "Bridge",          website: "https://across.to",                                          logo: "across.to" },
  { name: "Alchemy",              tagline: "Leading blockchain developer platform and infrastructure provider",                                               description: "Alchemy is the leading blockchain developer platform that powers millions of users in over 99% of countries worldwide. It provides the infrastructure, tooling, and resources developers need to build and scale decentralized applications.",                    twitter: "AlchemyPlatform",category: "Infrastructure",  website: "https://www.alchemy.com",                                    logo: "alchemy.com" },
  { name: "AllUnity",             tagline: "Regulated e-money institute building next generation digital payments infrastructure",                            description: "AllUnity is a regulated e-money institute (EMI) building next-generation digital payments infrastructure. It is a joint venture between DWS Group, Flow Traders, and Galaxy Digital focused on issuing regulated euro-denominated stablecoins.",               twitter: null,             category: "Stablecoin",      website: "https://allunity.com",                                       logo: "allunity.com" },
  { name: "Auros",                tagline: "Algorithmic trading and market making firm in digital assets",                                                    description: "Auros is a high-frequency trading and market making firm focused exclusively on digital assets. It provides liquidity across centralised and decentralised exchanges and is known for deep expertise in algorithmic strategies.",                              twitter: null,             category: "Trading",         website: "https://www.auros.global",                                   logo: "auros.global" },
  { name: "Avenia",               tagline: "Stablecoin infrastructure for the next generation of payments",                                                   description: "Avenia is building stablecoin infrastructure for the next generation of global payments, focused on making stablecoin issuance accessible, compliant, and efficient for financial institutions and fintechs around the world.",                              twitter: null,             category: "Stablecoin",      website: "https://avenia.io",                                          logo: "avenia.io" },
  { name: "AWS",                  tagline: "World's most comprehensive and broadly adopted cloud platform",                                                    description: "Amazon Web Services (AWS) is the world's most comprehensive and broadly adopted cloud platform, offering over 200 fully featured services from data centers globally. Millions of customers use AWS to lower costs, increase agility, and innovate faster.",  twitter: "awscloud",       category: "Infrastructure",  website: "https://aws.amazon.com",                                     logo: "amazon.com" },
  { name: "Axelar",               tagline: "Decentralized network and development platform securely connecting blockchains",                                  description: "Axelar delivers secure cross-chain communication for Web3. It enables dApp users to interact with any asset or application on any chain with one click. The network is built on proof-of-stake consensus and uses a set of protocols that enable cross-chain composability.", twitter: "axelarnetwork",  category: "Bridge",          website: "https://www.axelar.network",                                 logo: "axelar.network" },
  { name: "B2C2",                 tagline: "Institutional crypto liquidity provider and market maker",                                                        description: "B2C2 is an institutional liquidity provider in cryptocurrency markets. It offers OTC trading across spot and derivatives markets, providing liquidity solutions to banks, exchanges, brokers, hedge funds, and other institutional clients.",               twitter: "B2C2Group",      category: "Trading",         website: "https://www.b2c2.com",                                       logo: "b2c2.com" },
  { name: "Bank Frick",           tagline: "Blockchain-friendly private bank in Liechtenstein for digital asset businesses",                                  description: "Bank Frick is a family-owned Liechtenstein bank known for its expertise in blockchain banking. It provides banking services to crypto-native businesses and offers custody, trading, and settlement for digital assets under a fully regulated framework.",       twitter: null,             category: "Finance",         website: "https://www.bankfrick.li/en",                                logo: "bankfrick.li" },
  { name: "BDACS",                tagline: "Only institutional-grade digital asset custody service in Korea",                                                  description: "BDACS (Blockchain Digital Asset Custody Service) is South Korea's first and only institutional-grade digital asset custody service. It is operated by Korea Securities Depository and provides secure storage for digital assets under Korean regulatory oversight.", twitter: null,             category: "Custody",         website: "https://krw1.kr",                                            logo: "krw1.kr" },
  { name: "BitGo",                tagline: "Prime platform bringing trading, financing, collateral management, and settlement together",                       description: "BitGo is a digital asset financial services company providing institutional investors with security, compliance, and custodial solutions. It processes approximately 20% of all global Bitcoin transactions and supports over 800 tokens across 50+ blockchains.",  twitter: "BitGo",          category: "Custody",         website: "https://www.bitgo.com",                                      logo: "bitgo.com" },
  { name: "Bitso",                tagline: "Leading crypto exchange and stablecoin platform in Latin America",                                                 description: "Bitso is Latin America's leading cryptocurrency platform, offering services for individuals and businesses to buy, sell, send, and receive crypto. Its Juno infrastructure arm provides payment rails and stablecoin solutions for enterprises across the region.", twitter: "Bitso",          category: "Exchange",        website: "https://buildwithjuno.com/en-US",                            logo: "bitso.com" },
  { name: "Bitvavo",              tagline: "European cryptocurrency exchange for buying and selling digital assets",                                            description: "Bitvavo is a Netherlands-based cryptocurrency exchange regulated by De Nederlandsche Bank. It offers low-fee trading across hundreds of digital assets with a focus on the European market and strong compliance standards.",                              twitter: "Bitvavo",        category: "Exchange",        website: "https://bitvavo.com/en",                                     logo: "bitvavo.com" },
  { name: "BlackRock",            tagline: "World's largest asset manager providing investment management and tokenized asset solutions",                       description: "BlackRock is the world's largest asset manager with over $10 trillion in assets under management. It is pioneering tokenized asset products on blockchain, including its BUIDL fund — the world's largest tokenized money market fund.",                      twitter: "BlackRock",      category: "RWA",             website: "https://www.blackrock.com/us/individual",                    logo: "blackrock.com" },
  { name: "Blockdaemon",          tagline: "Institutional blockchain infrastructure for staking, nodes, and APIs",                                             description: "Blockdaemon is an institutional blockchain infrastructure provider offering node management, staking, and API services. It supports over 70 protocols and serves financial institutions, exchanges, and enterprises globally with enterprise-grade reliability.", twitter: "Blockdaemon",    category: "Infrastructure",  website: "https://www.blockdaemon.com",                                logo: "blockdaemon.com" },
  { name: "Blockradar",           tagline: "Enables fast, low-cost stablecoin money transfers for individuals across borders",                                  description: "Blockradar is a fintech platform enabling businesses to accept, send, and manage stablecoin payments across borders with low fees. It provides APIs and infrastructure for building crypto payment products in emerging markets, particularly across Africa.",    twitter: null,             category: "Payments",        website: "https://blockradar.co",                                      logo: "blockradar.co" },
  { name: "Blockscout",           tagline: "Open source blockchain explorer for EVM-compatible chains",                                                        description: "Blockscout is the leading open-source blockchain explorer for EVM-compatible networks. It provides full transparency into transactions, blocks, addresses, and smart contracts. Blockscout also offers RPC endpoints and serves as the official explorer for the Arc network.", twitter: "blockscoutcom",  category: "Analytics",       website: "https://www.blockscout.com",                                 logo: "blockscout.com" },
  { name: "BNY",                  tagline: "Global financial services firm providing investment management and banking",                                        description: "BNY (Bank of New York Mellon) is America's oldest bank and a leading global financial services company. With over $45 trillion in assets under custody, it is a key partner for institutional digital asset custody and tokenization initiatives.",          twitter: "BNYMellon",      category: "Finance",         website: "https://www.bny.com/corporate/global/en.html",               logo: "bny.com" },
  { name: "Brex",                 tagline: "AI-powered spend management platform for modern businesses",                                                        description: "Brex is an AI-powered spend management platform that helps businesses manage corporate cards, expense reports, and bill payments. It serves startups to enterprise companies with intelligent financial controls and global payment capabilities.",              twitter: "brexHQ",         category: "Finance",         website: "https://www.brex.com",                                       logo: "brex.com" },
  { name: "Bridge",               tagline: "Stablecoin platform built for developers enabling quick, easy global money movement",                              description: "Bridge is a stablecoin infrastructure platform acquired by Stripe. It enables businesses to issue stablecoins, accept stablecoin payments, and move money globally with simple APIs — making stablecoin adoption seamless for developers.",                   twitter: null,             category: "Payments",        website: "https://www.bridge.xyz",                                     logo: "bridge.xyz" },
  { name: "Bron",                 tagline: "Decentralized infrastructure for the next generation of financial systems",                                        description: "Bron is building decentralized infrastructure to power the next generation of financial systems. It focuses on creating permissionless and transparent financial primitives that can serve as the foundation for global capital markets.",                         twitter: null,             category: "Infrastructure",  website: "https://bron.org",                                           logo: "bron.org" },
  { name: "BTG Pactual",          tagline: "Leading Latin American investment bank and financial services group",                                               description: "BTG Pactual is Latin America's largest investment bank and leading financial services firm. It has been a pioneer in digital assets among traditional financial institutions, offering crypto funds, tokenized real estate, and blockchain-based products.",    twitter: "btgpactual",     category: "Finance",         website: "https://www.btgpactual.us",                                  logo: "btgpactual.com" },
  { name: "Bybit",                tagline: "Global cryptocurrency exchange offering spot, derivatives, and Web3 products",                                     description: "Bybit is one of the world's top three crypto exchanges by volume, offering spot, futures, options, and perpetual contract trading. It also provides Web3 wallets, NFT marketplaces, and a growing DeFi ecosystem to over 30 million registered users.",       twitter: "Bybit_Official", category: "Exchange",        website: "https://www.bybit.com/en",                                   logo: "bybit.com" },
  { name: "Careem",               tagline: "Super app for the greater Middle East providing everyday services",                                                 description: "Careem is the leading super app in the Middle East, North Africa, and Pakistan. Originally a ride-hailing company, it has expanded into food delivery, payments, and other everyday services across the region, serving millions of users.",                  twitter: "careem",         category: "Other",           website: "https://www.careem.com",                                     logo: "careem.com" },
  { name: "Catena Labs",          tagline: "Building AI-native financial infrastructure for the next generation",                                              description: "Catena Labs is building AI-native financial infrastructure, enabling AI agents to interact with financial systems autonomously and securely. It is founded by Circle veterans focused on the intersection of stablecoins and artificial intelligence.",            twitter: null,             category: "Developer Tools", website: "https://catenalabs.com",                                     logo: "catenalabs.com" },
  { name: "Centrifuge",           tagline: "Real-world asset protocol bringing institutional finance on-chain",                                                 description: "Centrifuge is the decentralized platform for real-world assets (RWA). It enables businesses to tokenize assets like invoices, real estate, and trade receivables to access DeFi liquidity, making institutional finance composable and transparent on-chain.",   twitter: "centrifuge",     category: "RWA",             website: "https://centrifuge.io",                                      logo: "centrifuge.io" },
  { name: "CFi",                  tagline: "Trade forex, stocks, indices, commodities, ETFs and more",                                                         description: "CFI Financial Group is a multi-regulated online brokerage offering access to over 15,000 financial instruments including forex, stocks, commodities, indices, and ETFs. It serves clients in over 100 countries with competitive spreads and fast execution.",   twitter: null,             category: "Trading",         website: "https://www.cfi.ag",                                         logo: "cfi.ag" },
  { name: "Chainlink",            tagline: "Leading decentralized oracle network serving as crucial blockchain infrastructure",                                 description: "Chainlink is the industry-standard decentralized oracle network that provides real-world data and off-chain computation to smart contracts. It secures tens of billions of dollars in DeFi and is used by hundreds of blockchain projects for reliable, tamper-proof data.", twitter: "chainlink",      category: "Oracle",          website: "https://chain.link",                                         logo: "chain.link" },
  { name: "Cloudflare",           tagline: "Global cloud platform securing and accelerating internet applications",                                             description: "Cloudflare is a global network designed to make everything you connect to the Internet secure, private, fast, and reliable. It provides DDoS protection, CDN, DNS, zero trust security, and developer tools to millions of websites and businesses worldwide.",   twitter: "Cloudflare",     category: "Infrastructure",  website: "https://www.cloudflare.com",                                 logo: "cloudflare.com" },
  { name: "Coinbase",             tagline: "Secure online platform for buying, selling, transferring, and storing cryptocurrency",                              description: "Coinbase is the most trusted cryptocurrency exchange in the United States, serving over 100 million verified users. It offers retail and institutional products including spot trading, staking, custody, prime brokerage, and the Base blockchain ecosystem.",  twitter: "coinbase",       category: "Exchange",        website: "https://www.coinbase.com",                                   logo: "coinbase.com" },
  { name: "Coincheck",            tagline: "Japan's leading cryptocurrency exchange for buying and trading digital assets",                                     description: "Coincheck is Japan's largest cryptocurrency exchange by trading volume and registered users. It offers trading for Bitcoin and over 20 altcoins, along with NFT marketplace and IEO services under full regulation by Japan's FSA.",                          twitter: "CoincheckJP",    category: "Exchange",        website: "https://coincheck.com",                                      logo: "coincheck.com" },
  { name: "Commerzbank",          tagline: "Leading bank for the German Mittelstand and partner to corporate client groups",                                   description: "Commerzbank is one of Germany's leading banks serving approximately 11 million private and corporate customers. It is actively engaged in digital asset custody and tokenization, having received a crypto custody license from BaFin in Germany.",             twitter: "Commerzbank",    category: "Finance",         website: "https://www.commerzbank.de/group",                           logo: "commerzbank.de" },
  { name: "Copper",               tagline: "Institutional-grade digital asset custody and prime brokerage",                                                    description: "Copper is an institutional digital asset infrastructure provider offering custody, prime brokerage, and settlement. Its ClearLoop technology enables off-exchange settlement, allowing institutions to trade on exchanges without moving assets off custody.",    twitter: null,             category: "Custody",         website: "https://copper.co/en",                                       logo: "copper.co" },
  { name: "Copperx",              tagline: "Accept stablecoin payments, open financial accounts, and send money globally",                                     description: "Copperx is a stablecoin payment platform that enables businesses to accept USDC and USDT payments, open financial accounts, and send money globally at low cost. It provides APIs and a dashboard for managing crypto payments and treasury operations.",       twitter: null,             category: "Payments",        website: "https://copperx.io",                                         logo: "copperx.io" },
  { name: "Corpay",               tagline: "Global payment solutions for businesses of all sizes",                                                              description: "Corpay is a global leader in business payments, providing solutions for accounts payable, corporate travel, and fleet management. It processes billions of dollars in payments annually and serves customers across more than 100 countries.",                    twitter: null,             category: "Payments",        website: "https://www.corpay.com",                                     logo: "corpay.com" },
  { name: "Crossmint",            tagline: "Enterprise blockchain infrastructure for NFTs, wallets, and payments",                                             description: "Crossmint is enterprise blockchain infrastructure that makes it easy to build NFT and token-based products. It provides APIs for minting NFTs, creating custodial wallets, and enabling crypto payments without requiring users to have wallets.",              twitter: "crossmint",      category: "Developer Tools", website: "https://www.crossmint.com",                                  logo: "crossmint.com" },
  { name: "Cumberland",           tagline: "Provides deep, dependable liquidity in cryptoassets",                                                              description: "Cumberland is a leading global digital asset trading firm and subsidiary of DRW. It provides institutional liquidity across spot and derivatives markets, serving exchanges, foundations, and other institutional clients with 24/7 OTC trading.",              twitter: "CumberlandSays", category: "Trading",         website: "https://www.cumberland.io",                                  logo: "cumberland.io" },
  { name: "Curve",                tagline: "Decentralized exchange optimized for stablecoin and low-slippage trading",                                         description: "Curve Finance is a decentralized exchange (DEX) optimized for efficient stablecoin trading with low fees and slippage. Its automated market maker (AMM) design makes it the backbone of DeFi stablecoin liquidity, processing billions in daily volume.",     twitter: "CurveFinance",   category: "DeFi",            website: "https://www.curve.finance",                                  logo: "curve.finance" },
  { name: "Deutsche Bank",        tagline: "One of the world's leading financial services providers",                                                           description: "Deutsche Bank is a global financial institution with deep roots in Germany and operations in over 58 countries. It is actively exploring blockchain for securities settlement, digital asset custody, and tokenization of real-world assets.",             twitter: "DeutscheBank",   category: "Finance",         website: "https://www.db.com",                                         logo: "db.com" },
  { name: "dLocal",               tagline: "Payments platform enabling businesses to accept and send money in emerging markets",                               description: "dLocal is a payments technology company focused on emerging markets. It enables global companies to accept payments from and send payments to consumers in markets across Africa, Asia, and Latin America using local payment methods and currencies.",        twitter: "dLocalGlobal",   category: "Payments",        website: "https://www.dlocal.com",                                     logo: "dlocal.com" },
  { name: "Dromos Labs",          tagline: "Builds decentralized systems and infrastructure for greater user control",                                          description: "Dromos Labs builds decentralized systems and infrastructure with a focus on giving users greater control over their digital assets and data. It contributes to open-source tooling and protocol development in the blockchain ecosystem.",                       twitter: null,             category: "Developer Tools", website: "https://dromos.xyz",                                         logo: "dromos.xyz" },
  { name: "dRPC",                 tagline: "Modular RPC solutions to launch, scale, and monitor blockchain infrastructure",                                    description: "dRPC is a decentralized RPC network offering modular infrastructure solutions for blockchain developers. It provides highly available, low-latency JSON-RPC endpoints across multiple chains with load balancing, monitoring, and pay-as-you-go pricing.",       twitter: null,             category: "Infrastructure",  website: "https://drpc.org",                                           logo: "drpc.org" },
  { name: "Dynamic",              tagline: "Flexible wallet and authentication platform for Web3 applications",                                                 description: "Dynamic is a flexible authentication and wallet platform for Web3 apps. It provides smart wallet creation, multi-chain login, embedded wallets, and passkey support — enabling seamless user onboarding without sacrificing security or flexibility.",      twitter: "dynamic_xyz",    category: "Wallet",          website: "https://www.dynamic.xyz",                                    logo: "dynamic.xyz" },
  { name: "EBANX",                tagline: "Payments platform enabling access to global commerce in emerging markets",                                          description: "EBANX is a global fintech company that enables businesses to access over 1 billion consumers in emerging markets across Latin America and Africa. It offers local payment methods, card processing, and payout solutions for global merchants.",              twitter: "EBANX",          category: "Payments",        website: "https://www.ebanx.com",                                      logo: "ebanx.com" },
  { name: "Elliptic",             tagline: "Blockchain analytics and crypto compliance solutions for institutions",                                             description: "Elliptic is a leading blockchain analytics company providing crypto compliance and risk management solutions to financial institutions, exchanges, and regulators. Its tools screen blockchain transactions for financial crime, sanctions, and illicit activity.", twitter: "elliptic",       category: "Analytics",       website: "https://www.elliptic.co",                                    logo: "elliptic.co" },
  { name: "Emirates NBD",         tagline: "Leading banking group in the Middle East and North Africa",                                                        description: "Emirates NBD is one of the largest banking groups in the Middle East with over AED 700 billion in total assets. It is a pioneer in digital banking innovation in the region and has been actively exploring blockchain and digital asset capabilities.",      twitter: "EmiratesNBD",    category: "Finance",         website: "https://www.emiratesnbd.com/en",                             logo: "emiratesnbd.com" },
  { name: "Exodus",               tagline: "Buy and sell crypto using credit card, bank account, Apple Pay, or Google Pay",                                    description: "Exodus is a leading self-custody crypto wallet supporting over 50 blockchain networks and thousands of assets. It offers an intuitive interface for managing, trading, and staking crypto across desktop and mobile — no account needed.",                     twitter: "exodus_io",      category: "Wallet",          website: "https://www.exodus.com",                                     logo: "exodus.com" },
  { name: "Fireblocks",           tagline: "Enterprise grade digital asset and stablecoin infrastructure powering financial possibility",                      description: "Fireblocks is the leading enterprise platform for digital asset operations. It provides MPC-based custody, policy management, tokenization infrastructure, and a network connecting 1,800+ institutions to move assets securely at scale.",                  twitter: "fireblocks",     category: "Custody",         website: "https://fireblocks.com",                                     logo: "fireblocks.com" },
  { name: "First Abu Dhabi Bank", tagline: "Provides corporate and institutional products to large corporate clients globally",                                description: "First Abu Dhabi Bank (FAB) is the UAE's largest bank and one of the largest financial institutions in the world. It offers corporate banking, investment banking, and capital markets services and has been active in digital asset exploration.",          twitter: null,             category: "Finance",         website: "https://www.bankfab.com/en-ae/personal",                     logo: "bankfab.com" },
  { name: "FIS",                  tagline: "Fintech transforming how we live, work and play through financial technology",                                     description: "FIS (Fidelity National Information Services) is a global leader in financial services technology, serving financial institutions, businesses, and developers worldwide. It processes trillions of dollars in transactions annually and enables digital transformation in banking and payments.", twitter: "FISGlobal",      category: "Finance",         website: "https://www.fisglobal.com",                                  logo: "fisglobal.com" },
  { name: "Fluid",                tagline: "Makes lending and borrowing on DeFi easier, safer, and more efficient",                                            description: "Fluid is a next-generation DeFi lending protocol that unifies liquidity across borrowing and DEX operations. Its innovative design allows collateral to be used as DEX liquidity simultaneously, dramatically improving capital efficiency for lenders and borrowers.",  twitter: null,             category: "Lending",         website: "https://fluid.io",                                           logo: "fluid.io" },
  { name: "Forte AUD",            tagline: "Simple, fast, cost-effective cryptocurrency access via Australian dollar stablecoin",                              description: "Forte AUD provides simple, fast, and cost-effective access to cryptocurrency through an Australian dollar-pegged digital asset. It offers a regulated AUD stablecoin solution designed for Australian individuals, businesses, and financial institutions.",      twitter: null,             category: "Stablecoin",      website: "https://www.forteaud.com",                                   logo: "forteaud.com" },
  { name: "Forte Securities",     tagline: "Independent global financial group offering brokerage, custody and asset management",                              description: "Forte Securities is an independent global financial services group offering brokerage, custody, and asset management. It serves institutional and professional clients with access to traditional and digital asset markets through regulated entities.",         twitter: null,             category: "Trading",         website: "https://fortesecurities.com",                                logo: "fortesecurities.com" },
  { name: "Fun.xyz",              tagline: "High converting rails to execute blockchain actions, optimize funding and reach customers",                         description: "Fun.xyz provides developer infrastructure enabling high-converting blockchain interactions. It offers wallet SDKs, fiat on-ramps, and user acquisition tools that help Web3 applications onboard users and optimize funding flows seamlessly.",            twitter: null,             category: "Developer Tools", website: "https://fun.xyz",                                            logo: "fun.xyz" },
  { name: "Galaxy",               tagline: "Global leader in digital assets and AI infrastructure serving institutions and startups",                          description: "Galaxy is a global leader in digital asset and AI infrastructure. It offers trading, asset management, investment banking, and mining services. Galaxy manages billions in assets and is a key institutional player in the cryptocurrency ecosystem.",        twitter: null,             category: "Finance",         website: "https://www.galaxy.com",                                     logo: "galaxy.com" },
  { name: "Goldman Sachs",        tagline: "Leading global investment banking, securities, and asset and wealth management firm",                              description: "Goldman Sachs is a leading global investment banking and financial services company. It has been actively building its digital asset capabilities including crypto trading, tokenization research, and blockchain-based financial product infrastructure.",      twitter: "GoldmanSachs",   category: "Finance",         website: "https://www.goldmansachs.com",                               logo: "goldmansachs.com" },
  { name: "Hashkey",              tagline: "Licensed digital asset exchange with institutional-grade security and compliance",                                  description: "HashKey Exchange is a licensed digital asset exchange regulated by the Hong Kong SFC. It offers spot trading, asset management, and custody services to retail and institutional clients, operating as one of Asia's most regulated crypto venues.",          twitter: null,             category: "Exchange",        website: "https://www.hashkey.com/en-US",                              logo: "hashkey.com" },
  { name: "Hecto Financial",      tagline: "Fintech company providing fintech platform services in South Korea",                                                description: "Hecto Financial is a leading South Korean fintech company providing payment processing, virtual account services, and digital financial infrastructure. It powers payments for thousands of businesses and is part of the broader Hecto Group.",              twitter: null,             category: "Finance",         website: "https://www.hectogroup.com",                                 logo: "hectogroup.com" },
  { name: "Hecto Innovation",     tagline: "IT platform company in the information security field primarily serving Korea",                                     description: "Hecto Innovation is an IT platform company specialising in information security and digital financial infrastructure in South Korea. It provides secure authentication, electronic document services, and fintech solutions to enterprises and financial institutions.", twitter: null,             category: "Infrastructure",  website: "https://www.hectogroup.com",                                 logo: "hectogroup.com" },
  { name: "HSBC",                 tagline: "British universal bank and financial services group headquartered in London",                                       description: "HSBC is one of the world's largest banking and financial services organisations, serving approximately 40 million customers across 60+ countries. It has been actively tokenizing real-world assets including gold and bonds on blockchain infrastructure.",   twitter: "HSBC",           category: "Finance",         website: "https://www.us.hsbc.com",                                    logo: "hsbc.com" },
  { name: "Hurupay",              tagline: "Get USD and EUR bank accounts to receive or send money globally",                                                   description: "Hurupay is a fintech platform that gives individuals and businesses access to USD and EUR bank accounts for sending and receiving money globally. It leverages stablecoins to provide fast, low-cost international transfers especially for emerging markets.", twitter: null,             category: "Payments",        website: "https://www.hurupay.com",                                    logo: "hurupay.com" },
  { name: "JPYC",                 tagline: "Stablecoin linked to the Japanese yen for NFT purchases and crypto exchange",                                      description: "JPYC is Japan's leading JPY-pegged stablecoin issuer. It provides a regulated yen-denominated digital asset for use in DeFi, NFT purchases, and crypto exchanges, helping bring Japanese yen liquidity on-chain in a compliant manner.",               twitter: null,             category: "Stablecoin",      website: "https://corporate.jpyc.co.jp/en",                            logo: "jpyc.co.jp" },
  { name: "Keyrock",              tagline: "Boosting digital assets with tailored liquidity solutions since 2017",                                              description: "Keyrock is a leading digital asset market maker and liquidity provider founded in 2017. It operates across 85+ exchanges and provides customised liquidity solutions for token projects, exchanges, and DeFi protocols globally.",                           twitter: null,             category: "Trading",         website: "https://keyrock.com",                                        logo: "keyrock.com" },
  { name: "Kraken",               tagline: "Own the power of your money — trading crypto, stocks, futures, staking and more",                                  description: "Kraken is one of the world's longest-standing and most trusted cryptocurrency exchanges. It serves over 10 million clients in 190+ countries with spot trading, futures, staking, and NFTs. Kraken Pro offers advanced trading tools for institutional traders.", twitter: "krakenfx",        category: "Exchange",        website: "https://www.kraken.com",                                     logo: "kraken.com" },
  { name: "Kyobo Life",           tagline: "Provides optimum insurance coverage and ongoing financial services in South Korea",                                  description: "Kyobo Life Insurance is one of South Korea's largest life insurance companies with over 12 million policyholders. It has been actively exploring blockchain and digital asset integration to enhance its financial product offerings.",                    twitter: null,             category: "Finance",         website: "https://www.kyobo.com/dgt/web/company-introduction/en-main", logo: "kyobo.com" },
  { name: "LayerZero",            tagline: "Builds technology making decentralization possible, scalable, and inevitable",                                      description: "LayerZero is an omnichain interoperability protocol that enables seamless communication between different blockchains. It powers cross-chain token transfers, governance, and messaging across 50+ chains and is used by hundreds of dApps.",              twitter: "LayerZero_Core", category: "Bridge",          website: "https://layerzero.network",                                  logo: "layerzero.network" },
  { name: "Ledger",               tagline: "Build your portfolio: buy, swap, stake, spend with hardware wallet security",                                       description: "Ledger is the world's leading hardware wallet company, with over 6 million devices sold. Its Ledger Live software enables users to manage 5,000+ assets, buy, swap, and stake crypto — all secured by the industry's most trusted cold storage hardware.",  twitter: "Ledger",         category: "Wallet",          website: "https://www.ledger.com",                                     logo: "ledger.com" },
  { name: "LianLian",             tagline: "Seamless and secure cross-border payment experience for global businesses",                                         description: "LianLian Global is a leading cross-border payments company enabling businesses to collect international payments, pay suppliers, and manage foreign exchange. It serves over 3 million e-commerce sellers and enterprises with fast, compliant global payment solutions.", twitter: null,             category: "Payments",        website: "https://lianlianglobal.com/en",                              logo: "lianlianglobal.com" },
  { name: "Maple",                tagline: "Onchain asset manager with decades of traditional finance and crypto experience",                                   description: "Maple Finance is an onchain credit marketplace where institutional and accredited investors can earn yield by lending to vetted borrowers. It brings traditional credit market expertise to DeFi, with over $2 billion in loans originated since launch.",     twitter: "maplefinance",   category: "Lending",         website: "https://maple.finance",                                      logo: "maple.finance" },
  { name: "Mastercard",           tagline: "American multinational payment card services corporation",                                                           description: "Mastercard is a global technology company connecting consumers, financial institutions, merchants, and governments through its payments network. It has been a leader in bridging traditional finance and digital assets through stablecoin and CBDC partnerships.",  twitter: "Mastercard",     category: "Payments",        website: "https://www.mastercard.com/us/en.html",                      logo: "mastercard.com" },
  { name: "Mercoin",              tagline: "Creates products helping people unleash potential and circulate value globally",                                    description: "Mercoin is the crypto arm of Mercari, Japan's largest marketplace app. It provides crypto trading services and blockchain infrastructure, helping everyday users access digital assets through familiar consumer apps.",                                     twitter: null,             category: "Finance",         website: "https://about.mercoin.com/en",                               logo: "mercoin.com" },
  { name: "MetaMask",             tagline: "Secure and flexible crypto wallet trusted by millions to buy, sell, and swap assets",                              description: "MetaMask is the world's most popular self-custodial crypto wallet with over 30 million monthly active users. It enables users to interact with the Ethereum ecosystem and thousands of dApps directly from their browser or mobile device.",                twitter: "MetaMask",       category: "Wallet",          website: "https://metamask.io",                                        logo: "metamask.io" },
  { name: "Morpho",               tagline: "Open credit network connecting lenders and borrowers to worldwide opportunities",                                   description: "Morpho is a decentralised lending protocol offering an open credit network where lenders and borrowers interact peer-to-peer. It improves on traditional money markets by optimising interest rates and capital efficiency without relying on centralised risk managers.", twitter: "MorphoLabs",     category: "Lending",         website: "https://morpho.org",                                         logo: "morpho.org" },
  { name: "Noah",                 tagline: "Unified API to easily integrate stablecoin payments into your platform",                                            description: "Noah provides a unified API that makes it easy for platforms to integrate stablecoin payments. It abstracts away the complexity of blockchain payments, enabling businesses to add USDC and other stablecoin payment rails in hours rather than months.",       twitter: null,             category: "Payments",        website: "https://noah.io",                                            logo: "noah.io" },
  { name: "Nuvei",                tagline: "Unifies pay-ins, payouts, and data on one intelligent payment platform",                                            description: "Nuvei is a Canadian fintech company providing payment technology solutions to businesses globally. It supports 700+ payment methods in 200 markets and has expanded into crypto payment acceptance and conversion for merchants.",                          twitter: "Nuvei",          category: "Payments",        website: "https://www.nuvei.com",                                      logo: "nuvei.com" },
  { name: "Pairpoint",            tagline: "Enables IoT devices to securely connect, transact, and communicate using SIM and blockchain",                      description: "Pairpoint by Vodafone is an IoT marketplace platform that uses SIM card identity and blockchain to enable IoT devices to autonomously transact and exchange data. It creates a trusted digital identity for connected devices at global scale.",             twitter: null,             category: "Infrastructure",  website: "https://pairpoint.io",                                       logo: "pairpoint.io" },
  { name: "Paysafe",              tagline: "Payment solution for every business helping SMEs grow",                                                              description: "Paysafe is a leading specialized payments platform serving merchants, consumers, and small businesses globally. It processes over $160 billion in payments annually across digital wallets, online cash solutions, and card processing in 120+ currencies.",   twitter: "Paysafe",        category: "Payments",        website: "https://www.paysafe.com",                                    logo: "paysafe.com" },
  { name: "PhotonPay",            tagline: "Simplify global business payments: accounts, cards, online payments, and embedded finance",                         description: "PhotonPay is a global business payments platform that provides multi-currency accounts, corporate cards, and cross-border payment solutions. It helps businesses collect revenue internationally and pay suppliers globally with transparent FX rates.",     twitter: null,             category: "Payments",        website: "https://www.photonpay.com",                                  logo: "photonpay.com" },
  { name: "Pimlico",              tagline: "Account abstraction infrastructure powering the Ethereum transition to smart accounts",                             description: "Pimlico is the leading account abstraction infrastructure provider. It powers smart account deployments across EVM chains with paymaster services for gas sponsorship, bundler infrastructure, and SDK tooling for ERC-4337 smart contract wallets.",      twitter: "pimlicoHQ",      category: "Infrastructure",  website: "https://www.pimlico.io",                                     logo: "pimlico.io" },
  { name: "Privy",                tagline: "Powers complete wallet stack from key management to user onboarding",                                               description: "Privy is a developer platform for powerful user authentication and embedded wallets. It enables apps to create wallets for users via email, social login, or passkeys — abstracting away seed phrases while maintaining self-custody principles.",             twitter: "privy_io",       category: "Wallet",          website: "https://www.privy.io",                                       logo: "privy.io" },
  { name: "QuickNode",            tagline: "Global network delivering real-time blockchain data with unmatched speed and reliability",                          description: "QuickNode is a leading blockchain infrastructure provider offering RPC endpoints, Streams, Functions, and marketplace add-ons for 30+ blockchains. Thousands of developers and enterprises rely on QuickNode for fast, reliable Web3 infrastructure.",    twitter: "QuickNode",      category: "Infrastructure",  website: "https://www.quicknode.com",                                  logo: "quicknode.com" },
  { name: "Rainbow",              tagline: "Explore NFTs and DeFi on Ethereum, Polygon, Optimism, Arbitrum, BSC, Base, and more",                             description: "Rainbow is a fun, simple, and secure Ethereum wallet that makes managing your assets and NFTs delightful. It supports multiple networks, DeFi connectivity, and token swapping — designed for both crypto newcomers and experienced users.",             twitter: "rainbowdotme",   category: "Wallet",          website: "https://rainbow.me/en-us",                                   logo: "rainbow.me" },
  { name: "Ramp",                 tagline: "AI-powered expense management platform simplifying spend management for businesses",                                description: "Ramp is a corporate card and expense management platform that helps businesses save money through AI-powered insights and automation. It offers corporate cards, bill payments, and vendor management with real-time spend controls.",                     twitter: "tryramp",        category: "Finance",         website: "https://www.ramp.com",                                       logo: "ramp.com" },
  { name: "Ramp Network",         tagline: "Seamless crypto buying, selling, and swapping within apps and wallets with full KYC",                              description: "Ramp Network is a fiat-to-crypto infrastructure provider that enables apps to offer seamless crypto purchase and selling experiences. It provides on-ramp and off-ramp solutions with global coverage and full KYC/AML compliance built in.",              twitter: "RampNetwork",    category: "Payments",        website: "https://rampnetwork.com",                                    logo: "rampnetwork.com" },
  { name: "RedStone",             tagline: "Modular oracle system providing customizable data feeds for DeFi protocols",                                        description: "RedStone is a modular oracle system delivering frequently updated, reliable, and diverse data feeds to smart contracts on 70+ blockchain networks. Its unique pull-based architecture reduces gas costs while enabling customisable data delivery for DeFi.",   twitter: "redstone_defi",  category: "Oracle",          website: "https://www.redstone.finance",                               logo: "redstone.finance" },
  { name: "Robinhood",            tagline: "Financial services company providing a trading platform for stocks, ETFs, and crypto",                              description: "Robinhood is a commission-free investing app serving over 23 million funded accounts. It offers stock, ETF, options, and crypto trading and has been expanding its digital asset capabilities with crypto wallets and on-chain trading features.",          twitter: "RobinhoodApp",   category: "Exchange",        website: "https://robinhood.com",                                      logo: "robinhood.com" },
  { name: "Sasai Fintech",        tagline: "Fintech and platform service provider empowering business growth through payments",                                 description: "Sasai Fintech is a leading African fintech company providing digital payment solutions, remittances, and financial services across sub-Saharan Africa. Its Sasai app offers mobile money, crypto, and communication features to millions of users.",        twitter: null,             category: "Payments",        website: "https://sasaifintech.com",                                   logo: "sasaifintech.com" },
  { name: "SBI Holdings",         tagline: "Financial services company group based in Tokyo, Japan",                                                            description: "SBI Holdings is a leading Japanese financial services conglomerate offering banking, securities, and insurance. It is one of Japan's most active investors in blockchain and crypto, operating its own exchange (SBI VC Trade) and crypto mining operations.", twitter: null,             category: "Finance",         website: "https://www.sbigroup.co.jp/english",                         logo: "sbigroup.co.jp" },
  { name: "Standard Chartered",   tagline: "Global bank connecting corporate and institutional clients to sustainable growth",                                  description: "Standard Chartered is an international banking group with a 170-year history, operating in the world's most dynamic markets. It has been a pioneer in institutional digital asset services, including crypto custody and tokenisation through its Zodia ventures.", twitter: "StanChart",      category: "Finance",         website: "https://www.sc.com/en",                                      logo: "sc.com" },
  { name: "Securitize",           tagline: "Leader in tokenizing real-world assets for institutional investors",                                                description: "Securitize is the leading platform for tokenizing real-world assets and managing digital securities. It is SEC-registered as a transfer agent and alternative trading system, and has tokenized assets for BlackRock, KKR, Hamilton Lane, and others.",      twitter: "Securitize",     category: "RWA",             website: "https://securitize.io",                                      logo: "securitize.io" },
  { name: "Sequence",             tagline: "Modular crypto infrastructure unifying wallets, cross-chain payments, and real-time data",                         description: "Sequence is a modular Web3 development platform offering smart wallets, marketplaces, analytics, and cross-chain infrastructure. It powers hundreds of Web3 games and apps with scalable, developer-friendly tools for user onboarding and in-app economies.", twitter: "0xsequence",     category: "Infrastructure",  website: "https://sequence.xyz",                                       logo: "sequence.xyz" },
  { name: "Societe Generale",     tagline: "European leader in financial services for over 150 years",                                                          description: "Société Générale is one of Europe's largest financial institutions, serving 25 million clients worldwide. Through its SG-Forge subsidiary, it has been a pioneer in digital asset issuance, tokenized bonds, and regulated crypto financial products.",       twitter: "SocieteGenerale",category: "Finance",         website: "https://www.societegenerale.com/en",                         logo: "societegenerale.com" },
  { name: "Stablecorp",           tagline: "Leading Canadian fintech building digital money infrastructure for global payments",                                 description: "Stablecorp is a leading Canadian fintech company that builds digital money infrastructure for global payments. It issues QCAD, Canada's first regulated Canadian dollar stablecoin, and provides white-label stablecoin solutions to financial institutions.", twitter: null,             category: "Stablecoin",      website: "https://www.stablecorp.ca",                                  logo: "stablecorp.ca" },
  { name: "Stargate",             tagline: "Bridge native USDC, USDT, ETH, BTC, and OFTs across 80+ chains",                                                  description: "Stargate is a composable liquidity transport protocol that enables native asset bridging across 80+ blockchain networks. Built on LayerZero, it allows users to move tokens like USDC and USDT cross-chain with instant finality and deep liquidity.",    twitter: "StargateFinance",category: "Bridge",          website: "https://stargate.finance",                                   logo: "stargate.finance" },
  { name: "State Street",         tagline: "Premier American financial holding company headquartered in Boston, MA",                                            description: "State Street is one of the largest custodian banks in the world with over $43 trillion in assets under custody. It is actively building digital asset capabilities including crypto custody, tokenized fund infrastructure, and blockchain-based settlement.",  twitter: "StateStreet",    category: "Finance",         website: "https://www.statestreet.com/us/en",                          logo: "statestreet.com" },
  { name: "Sumitomo Corporation", tagline: "Leading integrated trading company engaged in diverse businesses globally",                                         description: "Sumitomo Corporation is one of Japan's largest integrated trading companies, operating across infrastructure, transportation, media, finance, and real estate. It has been exploring blockchain and digital asset applications as part of its global business transformation.", twitter: null,             category: "Other",           website: "https://www.sumitomocorp.com/en/global",                     logo: "sumitomocorp.com" },
  { name: "Superface",            tagline: "LLM-powered automation agent connecting to systems and enabling task automation",                                   description: "Superface is an AI automation platform that connects LLMs to external tools and APIs. It enables AI agents to autonomously complete tasks across enterprise systems, using natural language interfaces to interact with databases, APIs, and business software.", twitter: null,             category: "Developer Tools", website: "https://superface.ai",                                       logo: "superface.ai" },
]

function toSlug(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const { password, mode } = body

    if (!password || password !== ADMIN_PASSWORD) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    // mode=update patches existing records with description, twitter, and logo
    if (mode === "update") {
      let updated = 0
      for (const p of ARC_PROJECTS) {
        await pool.query(
          `UPDATE projects
           SET description = $1, twitter = $2, logo_url = $3
           WHERE LOWER(name) = LOWER($4) AND badge = 'official'`,
          [p.description || null, p.twitter || null, `https://icon.horse/icon/${p.logo}`, p.name]
        )
        updated++
      }
      return NextResponse.json({ success: true, updated, total: ARC_PROJECTS.length })
    }

    // default mode: insert new records
    const [existingNamesRes, existingSlugsRes] = await Promise.all([
      pool.query(`SELECT LOWER(name) AS name FROM projects`),
      pool.query(`SELECT slug FROM projects`),
    ])
    const existingNames = new Set(existingNamesRes.rows.map((r: any) => r.name as string))
    const existingSlugs = new Set(existingSlugsRes.rows.map((r: any) => r.slug as string))

    const toInsert: { name: string; tagline: string; description: string; category: string; logo_url: string; website: string; slug: string; twitter: string | null }[] = []
    let skipped = 0

    for (const p of ARC_PROJECTS) {
      if (existingNames.has(p.name.toLowerCase())) { skipped++; continue }

      let slug = toSlug(p.name)
      const base = slug
      let i = 1
      while (existingSlugs.has(slug)) slug = `${base}-${++i}`
      existingSlugs.add(slug)

      toInsert.push({
        name:        p.name,
        tagline:     p.tagline,
        description: p.description || "",
        category:    p.category,
        logo_url:    `https://logo.clearbit.com/${p.logo}`,
        website:     p.website,
        slug,
        twitter:     p.twitter || null,
      })
    }

    if (toInsert.length > 0) {
      const placeholders = toInsert.map((_, i) => {
        const b = i * 8
        return `($${b+1},$${b+2},$${b+3},$${b+4},$${b+5},$${b+6},$${b+7},$${b+8},'official',true,true,false)`
      }).join(",")

      const params = toInsert.flatMap(p => [p.name, p.tagline, p.description, p.category, p.logo_url, p.website, p.slug, p.twitter])

      await pool.query(
        `INSERT INTO projects (name, tagline, description, category, logo_url, website, slug, twitter, badge, approved, live, featured)
         VALUES ${placeholders}`,
        params
      )
    }

    return NextResponse.json({
      success:  true,
      inserted: toInsert.length,
      skipped,
      total:    ARC_PROJECTS.length,
    })
  } catch (err) {
    console.error("[SeedArc]", err)
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
